# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel_app
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
#     networks:
#       - laravel_network
#     depends_on:
#       - db
#     # Tidak perlu expose port 9000 ke host jika hanya digunakan oleh nginx
#     # ports:
#     #   - "9000:9000"  
#     command: [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=9000" ]

#   db:
#     image: mysql:8.0
#     container_name: laravel_db
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: F11sabilillah!
#       MYSQL_DATABASE: pos-db
#       MYSQL_USER: posadmin
#       MYSQL_PASSWORD: F11sabilillah!
#     volumes:
#       - dbdata:/var/lib/mysql
#     networks:
#       - laravel_network

#   web:
#     image: nginx:alpine
#     container_name: laravel_nginx
#     volumes:
#       - .:/var/www
#       - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - "8080:80" # Port Nginx untuk mengakses aplikasi dari luar
#     networks:
#       - laravel_network
#     depends_on:
#       - app

# volumes:
#   dbdata:

# networks:
#   laravel_network:
#     driver: bridge

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: F11sabilillah!
      MYSQL_DATABASE: pos-db
      MYSQL_USER: posadmin
      MYSQL_PASSWORD: F11sabilillah!
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - app

volumes:
  dbdata:


networks:
  laravel_network:
    driver: bridge
