version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app1
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: laravel_db_app1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: F11sabilillah!
      MYSQL_DATABASE: pos-db-app1
      MYSQL_USER: posadmin
      MYSQL_PASSWORD: F11sabilillah!
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_app1
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app1
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: F11sabilillah!
    ports:
      - "8081:80"
    networks:
      - laravel_network

volumes:
  dbdata:

networks:
  laravel_network:
    driver: bridge
